### ISSUE TITLE
Simplify duplicate screen a little bit

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#118]
It's a bit weird as it is, couldn't you just ask which one you want to keep and place a button to keep both on bottom?

**Comment by K1rakishou** [comment]
That's what it is asking you, though? You can choose how to process each image: save from the server again and overwrite the local one, leave the local one as is or save the server image with a different name like image_(1).jpg. Clicking the image of a row will apply the setting to an individual image, clicking the check box will apply the setting to all images.
