### ISSUE TITLE
SLOW LOADINGS

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#129]
APLLYING FLITER SLOW LOADING NEED TO FIXED IMMEDIATELY
SOME CERTAIN BOARD CAN'T ACCESS CUZ OF THIS
MORE SLOWER THAN SONIC 06 LOADING SCREEN
CAN YOU FIX IT PLEASE?

THANK YOU

**Comment by K1rakishou** [comment]
Duplicate of https://github.com/KurobaExReports/Reports/issues/128
