### ISSUE TITLE
Reply window behavior 

### ISSUE THREAD

**Issue by kidddd66** [KurobaExReports/Reports#131]
Just updated to the latest f-Droid version 1.3.6.
Not sure what version I was on (1.3.5 maybe?) prior the update but I think the replies window's behavior changed (or I didn't notice it beforehand). It starts small until the post loads, then it gets bigger [Screen record](https://files.catbox.moe/19omyq.mp4)
Android animations are on default speed (1x) 

Steps to reproduce:
1. Find a post with at least 1 reply (so the button shows) 
2. Click the button and watch how the window starts small and gets bigger when the reply fully loads (especially visible with replies with large text)

**Comment by K1rakishou** [comment]
Yeah, that's a side effect of fixing a memory leak related to post popups. Unfortunately, it will stay like this until I figure out another way of fixing the memory leak. 
Also this repository is for reports made by the in-app reporting system. Actual issues should be created in the main repository.

**Comment by K1rakishou** [comment]
Closing this one in favor of https://github.com/K1rakishou/Kuroba-Experimental/issues/736
