### ISSUE TITLE
Date and Anonymous names not showing up

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#143]
I updated Kuroba today and suddenly the dates, file descriptions, and anonymous names all defaulted to being disabled. Despite deactivating and reactivating the sliders for these and restarting the app it didn't do anything

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/5188a1d28f9099daced004def9d0f984e7dde547
