### ISSUE TITLE
Make the date format independent of system locale

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#144]
Respecting  the system locale is cool but being able to set one different from it would be better. Could either be a list with different options like YYYY-MM-DD, DD-MM-YYYY etc. or something like 4chan-x that allows you to write your own format with %d, %m

**Comment by K1rakishou** [comment]
There is already an issue for that https://github.com/K1rakishou/Kuroba-Experimental/issues/498
