### ISSUE TITLE
Using system locale post dates causes weird line breaks. 

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#156]
When using the new system locale option to display the full date on posts, often times the seconds of the time display will overflow onto a new line. I use 17 point text, presumably this error only occurs when using bigger than normal text size. 
Locking the post information to a certain font size seems like a potential fix, this is how it works in Kuroba. It isn't really necessary to have the date\post info be as big as the post text itself.

**Comment by K1rakishou** [comment]
I don't think I can do anything here. That's how the text works, it overflows onto the next line if there is not enough space. Make the font size smaller.
