### ISSUE TITLE
Convenient access to KurobaExReports

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#28]
Please add a link to the new KurobaExReports bug tracker inside the app for easier access

I suggest to add it below the "Find KurobaEx-beta on GitHub" button in the settings, or a sub dialog to that button which asks if the user is looking for the source code or the bug tracker

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/a48b13431ec9e03629c9656902b186796c9ce40a
