### ISSUE TITLE
Feature - Open links in custom tabs

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#338]
https://developer.chrome.com/docs/android/custom-tabs/

**Comment by K1rakishou** [comment]
What's the profit of using this instead of just opening links in the browser?

**Comment by KurobaExReports** [comment]
Opens way faster on shit phones and it's faster to go back where you were, doesn't clutter your tabs/history when you just want to take a quick peek, etc. You can always open it on the browser by tapping on top right -> open on browser. I think Clover even used this by default, but there's a long time since I used it so I don't remember very well.

**Comment by K1rakishou** [comment]
You need a separate dependency for that, though. I don't think it's worth it.

**Comment by KurobaExReports** [comment]
Kuroba used this too and it was pretty nice

**Comment by K1rakishou** [comment]
Yeah and it used that separate dependency. 

>implementation "androidx.browser:browser:1.3.0"

Also it probably only works with Chrome (not sure).
