### ISSUE TITLE
Third eye

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#350]
I'm pretty sure before you could just import a setting to get it working, now you have to type all that? Can't you just bundle a few presets and enable the importing again?
Also why it's so hidden, I had to search for the setting for like 5 minutes before stumbling upon it.

**Comment by KurobaExReports** [comment]
nvm, I want to say I'm retarded but that's not great UX mate, that icon is usually used to order/arrange stuff, not to import/export. Presets would still be a nice addition tho

**Comment by K1rakishou** [comment]
The icon is literally called ic_baseline_import_export_24 so I have no idea what you are talking about.
