### ISSUE TITLE
nightly/dev builds for KurobaExLite?

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#386]
I want to test it

**Comment by K1rakishou** [comment]
You already can. https://github.com/K1rakishou/KurobaExLite/releases
There are some performance issues in the latest release and some bugs that are already fixed but not released yet, though.

**Comment by KurobaExReports** [comment]
I mean, that's a build from 8 days ago, wouldn't call it a nightly

**Comment by K1rakishou** [comment]
Well there are no nightly builds, as in builds that are made every day.
