### ISSUE TITLE
Draw the thread behind the image when the media viewer is open

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#40]
I believe this was the previous behavior, that when you opened an image it'd still show the thread behind it, so you could see it scrolling as you swiped through images. Now it has a fully black bg so that isn't possible. It's especially bad on light themes since you go from having a light colored UI to everything being black.
I think that reverting to the previous settings, or at least adding an alpha transparency slider would be much better.

**Comment by K1rakishou** [comment]
I remember there were some weird glitches caused by the transparent activity background when I was trying to add mpv support so I decided to make it completely black.
