### ISSUE TITLE
You can't report posts because you are banned?

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#405]
I'm not even at home where my IP is banned for 2 days. It doesn't affect posting, just reporting. Already cleared app cache, didn't solve it.

**Comment by K1rakishou** [comment]
>Already cleared app cache

You need to clear cookies. Clearing the cache doesn't clear them. Can be done in the site settings.

**Comment by KurobaExReports** [comment]
If I report in WebView it werks
