### ISSUE TITLE
Loading wheel or video player button is slightly off-center

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#429]
it's noticeable on slow connections, one of the is not exactly on the center of the screen

**Comment by K1rakishou** [comment]
Which loading wheel? Show screenshot.

**Comment by KurobaExReports** [comment]
The download one, just go to /wsg/ and start opening random webms. Can't attach pics from this report form afaik

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/a20af2454bc023d403b4f31685e22f48be2cd2e2
