### ISSUE TITLE
meme flags

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#497]
there is no option to filter meme flaggots. please rectify this in a future update.

**Comment by K1rakishou** [comment]
You can. Read the filtering FAQ.

**Comment by awelton85** [comment]
> You can. Read the filters FAQ.

Where is this FAQ located?

**Comment by K1rakishou** [comment]
When you click the "create filter" button (the round one with the "+" sign on it) there will be an "(?)" icon in the top right corner.
