### ISSUE TITLE
Can you make third eye a bit more accessible?

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#524]
I mean, drop downs with some preset websites would be pretty good. It's painful to set it up by hand and I doubt most people will have any idea of how to even begin.

**Comment by K1rakishou** [comment]
Just use this config.
https://pastebin.com/raw/gVt9jr3n

**Comment by KurobaExReports** [comment]
I know about this, but it's not user friendly. Someone would've to dig through reports to even find it. Why not just ship it in the app?

**Comment by K1rakishou** [comment]
Because I don't want to include it into the app. The whole idea was to make it separate from the app.

**Comment by KurobaExReports** [comment]
Well that's gay. You could at least place it on the app's wiki
