### ISSUE TITLE
Can you make the side bar work a bit more like Kuroba's?

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#525]
With swipe to delete bookmarks, tapping on the thread's image or post count to stop tracking, a bit of padding on top so it's easier to reach on big phones and infos like replies, IPs, current page.
A separated page to access all the history would be nice too, I'd not like to have all my history there, but having to choose between having just bookmarks and tracking history is not cool.

**Comment by K1rakishou** [comment]
No. However, you can try this app https://github.com/K1rakishou/KurobaExLite the drawer is closer to Kuroba's version in it (but you still can't swipe to delete bookmarks there either because that's not possible in Jetpack Compose which is used for everything UI related there)
