### ISSUE TITLE
(Third eye) Let me choose between showing both pics or original and a +1

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#526]
It seems to be inconsistent in the current implementation, when the third eye pic is loaded it is placed on the right side of the original, after reloading the thread it is placed behind the original with a +1, showing that it exists. It would be great if we could choose which behavior we want.

**Comment by K1rakishou** [comment]
I don't get what you mean. The "+1" is configured by "Post multiple images compact mode". Change it if you want to see all the images in the post.

**Comment by KurobaExReports** [comment]
That's what I meant
https://files.catbox.moe/nsrr7g.mp4

**Comment by K1rakishou** [comment]
Can you link the thread? Seems like a bug that's caused by the media prefetching.

**Comment by K1rakishou** [comment]
Also, it's probably going to be easier if you just send me your app backup because the problem is most likely in a specific combination of settings. I tried to use media prefetcher but couldn't reproduce the bug so it's probably some other settings affecting it.

**Comment by KurobaExReports** [comment]
That was weeks ago, if I see it happening again I'll let you know

**Comment by KurobaExReports** [comment]
It's caused by media prefetch, I can reliability reproduce it on >>>/vp/51244190

**Comment by K1rakishou** [comment]
Yeah, I tried that already but couldn't reproduce.

**Comment by KurobaExReports** [comment]
what if I tell you I was about to send you my settings but I can't reproduce it anymore lol

**Comment by K1rakishou** [comment]
Weird.
