### ISSUE TITLE
Can't show posts with >>0

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#530]
If a post has >>0 (which can happen when quoting a line that starts with >0 for instance) the app shows a blank post. Easily reproducible, just make a post starting with >>0 and then anything else and the app will show it as a blank post.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/90e2fda427948820fff580055a0ad48dc5a17b57
