### ISSUE TITLE
Question about themes

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#532]
I was just fucking around making my own themes and got a bit confused, what defines the color of these things being pointed by a pink arrow?
btw, I think there's a bug related to the image background on the theme preview, keep switching between Tomorrow Classic and Tomorrow Black and you'll see that the color of their backgrounds keeps changing (yellow arrow).

Image for reference
https://imgur.com/a/saSmnbS

**Comment by K1rakishou** [comment]
>what defines the color of these things being pointed by a pink arrow?

It's calculated programmatically based on `primaryColor`

```
      val uncheckedColor = if (ThemeEngine.isNearToFullyBlackColor(themeEngine.chanTheme.primaryColor)) {
        android.graphics.Color.DKGRAY
      } else {
        ThemeEngine.manipulateColor(themeEngine.chanTheme.primaryColor, .7f)
      }
```

If `primaryColor` is very dark then  android.graphics.Color.DKGRAY is used (0xFF444444) otherwise `primaryColor` is converted into a darker variant (like 35% darker?).

>btw, I think there's a bug related to the image background on the theme preview, keep switching between Tomorrow Classic and Tomorrow Black and you'll see that the color of their backgrounds keeps changing (yellow arrow).

Because `backColorSecondary` is used to draw that background.

**Comment by KurobaExReports** [comment]
So I can't change it? :/
I wanted to make a theme close to Tomorrow Classic but dark buttons on dark background looks pretty ugly imo, and pretty hard to see on my phone. Maybe you could make it an optional flag or make the black detection a bit more lenient please?

**Comment by K1rakishou** [comment]
No, you can't change it.
