### ISSUE TITLE
captcha solver as a plugin

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#559]
better than having a stub app sitting on the launcher

**Comment by K1rakishou** [comment]
I can only do that with dynamic libraries (so files) not apks. In other words I would have to rewrite all that shit in C/C++/other compiled language and obviously I'm not going to do that.

**Comment by KurobaExReports** [comment]
There's really no other solution more elegant than having a separate app?

**Comment by K1rakishou** [comment]
The official way is to just embed everything into the main apk. I don't want to do this because it will increase the apk size by 50 megabytes and not everyone needs a captcha solver, people uses passcodes too. I don't really see a problem here, just leave it alone, you don't even need to open it once.

**Comment by KurobaExReports** [comment]
How about an option to hide it from the launcher then? It's possible, I've seen many apps doing it. Tachiyomi plugins for example are apks and don't show up

**Comment by K1rakishou** [comment]
I think if I hide the icon from the launcher people will start saying that it's a spyware or some other shit. At least like this they can see it and always remove it by long tapping the icon.

**Comment by KurobaExReports** [comment]
You can put an option inside the app itself, I've seen apps doing that too.
>At least like this they can see it and always remove it by long tapping the icon.
Most stock launchers don't have this option.

Maybe this can help if you are willing to do it 
https://stackoverflow.com/questions/19114439/android-hide-unhide-app-icon-programmatically/22754642#22754642
