### ISSUE TITLE
Bad status: 503 on Captcha request

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#567]
There's now a Cloudflare check on captcha requests so KurobaEx can't display it anymore

**Comment by K1rakishou** [comment]
It should auto-pass it if you are on the latest version of the app. 
Thank God I decided to refactor that shit recently and now it should "just work".

**Comment by zaldhyx77** [comment]
im on latest version and still cant load captcha

**Comment by K1rakishou** [comment]
Should be fixed by https://github.com/K1rakishou/Kuroba-Experimental/commit/6959ad1cbd1a6b65a46d9dac409a5bae93e2d8b6
