### ISSUE TITLE
Request - Proper bookmarks on side pane

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#580]
Why do I have to choose between having history or bookmarks? It doesn't make much sense. Also is there really no better way to unbookmark? On Kurobadev you can just slide instead of having to tap and hold or open other screens...

**Comment by K1rakishou** [comment]
If you really can't live without bookmarks being located in the drawer then the only suggestion I can give you is to try this reimagination of KurobaEx https://github.com/K1rakishou/KurobaExLite 
There is no CloudFlare support yet, though, so you won't be able to post for some time.
