### ISSUE TITLE
Newline key missing on keyboards

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#594]
After updating the app from 1-2 versions ago to fix the captcha cloudflare issue I'm now missing a line break key on both GBoard and Hacker's Keyboard, it shows a "Next" key that changes focus away from the text box. The input box also seems to display multi line text when pasted as a single line, though the line breaks are there once posted
(btw line breaks and the enter button are working fine in this report input box)

**Comment by K1rakishou** [comment]
https://github.com/K1rakishou/Kuroba-Experimental/issues/805
