### ISSUE TITLE
(Feature Request) Create themes inside app

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#597]
Some tool with color pickers and such, so you don't need a PC

**Comment by K1rakishou** [comment]
I have already provided too many instrument to build themes.
See https://github.com/K1rakishou/KurobaEx-theme-builder
No, I'm not going to embed it into the app.

**Comment by KurobaExReports** [comment]
Come on, not even something like this? Just give variables friendly names. This way people can just download some color picker app and play around by pasting the colors and applying the theme.

mockup 
https://files.catbox.moe/li8m6g.png
