### ISSUE TITLE
(Request) Community localization

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#598]
Create a Crowdin/Transifex where community can translate app to more languages. Most of users are fine with English but some don't understand some options.

**Comment by K1rakishou** [comment]
This probably won't work that easy because:
1. There are hardcoded strings in the code itself. And there are a lot of them.
2. Since I never expected on adding other languages a lot of UI controls have hardcoded dimensions so adding new language will break a lot of stuff.
