### ISSUE TITLE
How do I reorder bookmarks on the side panel?

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#600]
Excuse me but I can't find an option

**Comment by K1rakishou** [comment]
You can't because those are technically not bookmarks.

**Comment by KurobaExReports** [comment]
Not even after enabling "display bookmarked threads"?

**Comment by K1rakishou** [comment]
No, that's a hack to make history look like bookmarks. Actual bookmarks are on the Bookmarks page.
