### ISSUE TITLE
Bookmark sorting by creation time actually sorts by bookmarked time

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#609]
Like the title says, sorting by creation time doesn't sort by thread creation time, but by bookmarked time (so un-bookmarking and redoing it actually changes the order)

**Comment by K1rakishou** [comment]
That's the intended behavior.

**Comment by KurobaExReports** [comment]
Can you make it clearer on and maybe add a way to sort by thread creation time then? 
The 4chan X thread watcher (and I think the vanilla one too) orders by board and then by thread creation time so it's more natural

**Comment by K1rakishou** [comment]
I don't store thread creation date in the bookmark info.

**Comment by KurobaExReports** [comment]
But you store their post #, right? So you can just group by board (either alphabetical, like vanilla extension, or by added order, like 4chanx) and then sort them by post number.

**Comment by K1rakishou** [comment]
Yeah, I guess using thread number should work for that.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/3abf80427228bd2b2f5ae9b122b2363cff2405ef
