### ISSUE TITLE
This error when you tap a cross thread link in an archive

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#627]
desuarchive if that matters
https://i.imgur.com/c5WBldR.jpg

**Comment by K1rakishou** [comment]
Can you post the thread link?

**Comment by KurobaExReports** [comment]
I don't have it anymore, but I think you can find it by searching one of these post numbers on the archive

**Comment by K1rakishou** [comment]
Kinda fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/1f89e3556910b3b7f07a32b8917b2f6576586b4e
Those kinds of links will now be opened through the browser.
