### ISSUE TITLE
Just force low ram mode for shit devices at this point

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#672]
Jesus Christ

**Comment by K1rakishou** [comment]
Are you the guy with lots of OOM crashes? There is already low ram mode and it's forced for everyone with Android <= 6.

**Comment by KurobaExReports** [comment]
I'm not, just seeing all these reports from the last few weeks. But I did have a 1GB in the past and it would crash at times without the low ram mode.

**Comment by K1rakishou** [comment]
Well that dude has even less ram (like 768 megabytes).
