### ISSUE TITLE
Image viewer keeps screen on forever.

### ISSUE THREAD

**Issue by miskig** [KurobaExReports/Reports#734]
The image browser in a thread will keep the screen on forever. 

This is the Fullscreen browser with swipe left/right and up/down to save or exit.

There appears to be no setting to control this, (or I'm dumb)

Steps to reproduce: pick an image board, thread and image, tap to view, possibly swipe a few times -- then set phone down. 

Screen will never timeout.

**Comment by K1rakishou** [comment]
I think this one can be closed since this one https://github.com/K1rakishou/Kuroba-Experimental/issues/821 exists.
