### ISSUE TITLE
Captcha not loading when using mobile data

### ISSUE THREAD

**Issue by Hlodwig27** [KurobaExReports/Reports#83]
Captcha is giving an error when i try to post with mobile data. It works fine with wifi.

I already deleted the caché and restarted the app.

At last, thank you for your work.

![Screenshot_20220204-210049](https://user-images.githubusercontent.com/46011285/152618867-b54adfec-0a74-4bab-a82b-cdbe33267a8f.png)
![Screenshot_20220204-210044](https://user-images.githubusercontent.com/46011285/152618872-865b25f0-377b-4265-9512-6f22d30d3f4f.png)

**Comment by K1rakishou** [comment]
Something is wrong with your connection. Maybe the domain is blocked by the ISP or something like that.
